// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelrySalesStoreData.Models;

public partial class Category
{
    public Guid CategoryId { get; set; }

    public string Name { get; set; }

    public string Material { get; set; }

    public string ProductLine { get; set; }

    public string Collection { get; set; }

    public string FengShui { get; set; }

    public string Purpose { get; set; }

    public bool? Gender { get; set; }

    public bool? IsActive { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}