// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelrySalesStoreData.Models;

public partial class Customer
{
    public Guid CustomerId { get; set; }

    public string CustomerFirstName { get; set; }

    public string CustomerLastName { get; set; }

    public bool? CustomerGender { get; set; }

    public DateTime? CustomerBirthDate { get; set; }

    public string CustomerPhone { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerAddress { get; set; }

    public double? CustomerPoint { get; set; }

    public bool? CustomerVipStatus { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}