// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelrySalesStoreData.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public Order()
    {
        OrderId = Guid.NewGuid();
    }

    public Guid? CustomerId { get; set; }

    public Guid? CompanyId { get; set; }

    public DateTime? Date { get; set; }

    public double? TotalPrice { get; set; }

    public string PaymentMethod { get; set; }

    public string ShippingMethod { get; set; }

    public string CustomerAddress { get; set; }

    public string CustomerBankAccount { get; set; }

    public bool Status { get; set; }

    public string Notes { get; set; }

    public virtual Company Company { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}