// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations; 
using System.ComponentModel.Design;
using System.Collections.Generic;

namespace JewelrySalesStoreData.Models
{
    public partial class OrderDetail
    {
        public Guid OrderDetailId { get; set; }

        public OrderDetail()
        {
            OrderDetailId = Guid.NewGuid();
        }

        public Guid? OrderId { get; set; }

        public Guid? ProductId { get; set; }

        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than zero")]
        public int? Quantity { get; set; }

        [Required(ErrorMessage = "Unit price is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Unit price must be greater than zero")]
        public double? UnitPrice { get; set; }

        [Required(ErrorMessage = "Total price is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Total price must be greater than zero")]
        public double? TotalPrice { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Discount price cannot be negative")]
        public double? DiscountPrice { get; set; }

        [Required(ErrorMessage = "Final price is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Final price must be greater than zero")]
        public double? FinalPrice { get; set; }

        public bool IsActive { get; set; }

        public string Notes { get; set; }

        public virtual Order Order { get; set; }

        public virtual Product Product { get; set; }
    }
}
