// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace JewelrySalesStoreData.Models;

public partial class Promotion
{
    public Guid PromotionId { get; set; }

    [Required]
    [Display(Name = "Promotion Name")]
    public string PromotionName { get; set; }

    [Required]
    public string PromotionCode { get; set; }

    [Required]
    [Display(Name = "Discount Percentage")]
    public double DiscountPercentage { get; set; }

    [Required]
    [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = false)]
    public DateTime? StartDate { get; set; }

    [Required]
    [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = false)]
    public DateTime? EndDate { get; set; }

    public string Condition { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}